package projekt.MPISCore.Kompozicija;

public enum Tip_signala {
	DV_TRENUTNO, SP_TRENUTNO, DV_SVE, SP_SVE, DV_DESNI, DV_LIJEVI, SP_LIJEVI, SP_DESNI,
	SP_PREKIDAC, DV_PREKIDAC, DV_UZEMLJENJE, DV_PRAVO_UZEMLJENJE
}
